lang: ru
bibliography: references.bib
csl: include/gost-r-7-0-5-2008-numeric.csl
format:
  pdf:
    titlepage: false
    toc: false
    cite-method: citeproc
    link-citations: true
    documentclass: article
    papersize: a4
    mainfont: Times New Roman
    fontsize: 14pt
    linestretch: 1.5
    geometry:
       - left=25mm
       - top=20mm
       - right=20mm
       - bottom=20mm
    indent: true
    number-sections: true
    crossref:
      tbl-title: "Таблица"
      fig-title: "Рисунок"
      eq-title: "Формула"
      tbl-prefix: "табл."
      fig-prefix: "рис."
      eq-prefix: "формула"
    pdf-engine: xelatex
    include-in-header:
      - include/13-2016-2-gost.sty
      - titledata.tex
      - include/titlepage.tex
      - include/toc.tex
      - include/code_blocks.tex
